---
- name: Créer un endpoint en Cisco ISE via l'API REST
  hosts: Cisco ISE Group
  gather_facts: no
  tasks:
    - name: Vérifier l'accessibilité de l'API
      ansible.builtin.uri:
        url: "https://161.1.7.221:9060/ers/config/endpoint"
        method: GET
        headers:
          Accept: "application/json"
          Authorization: "Basic YWRtaW46T251dGVjaDEyMy4="
        validate_certs: no
      register: api_access_check

    - name: Afficher le résultat de l'accessibilité de l'API
      debug:
        var: api_access_check

    - name: Créer un endpoint
      ansible.builtin.uri:
        url: "https://161.1.7.221:9060/ers/config/endpoint"
        method: POST
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
          Authorization: "Basic YWRtaW46T251dGVjaDEyMy4="
        body: >
          {
            "ERSEndPoint": {
              "name": "asa",
              "description": "MyEndpoint",
              "mac": "50:32:34:48:95:36",
              "groupId": "aa13bb40-8bff-11s6-946c-525400b48591",
              "staticGroupAssignment": true
            }
          }
        body_format: json
        validate_certs: no
      register: result
      when: api_access_check.status == 200

    - name: Afficher le résultat de la création de l'endpoint
      debug:
        var: result
