---
- name: Créer un profil d'autorisation via l'API REST
  hosts: Cisco ISE Group
  connection : httpapi
  become : false
  gather_facts: no
  tasks:
    - name: Créer un profil d'autorisation
      ansible.builtin.uri:
        url: "https://161.1.7.221:9060/ers/config/authorizationprofile"
        method: POST
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
          Authorization: "Basic YWRtaW46T251dGVjaDEMy="
        body: >
          {
            "AuthorizationProfile": {
              "id": "9988776655",
              "name": "ProfilAuthorization",
              "description": "Description",
              "accessType": "ACCESS_ACCEPT",
              "authzProfileType": "SWITCH",
              "vlan": {
                "nameID": "200",
                "tagID": 1
              },
              "trackMovement": false,
              "agentlessPosture": false,
              "serviceTemplate": false,
              "easywiredSessionCandidate": false,
              "coaType": "DEVICE",
              "autoSmartPort": false,
              "daclName": "SampleDACL",
              "airespaceACL": "SampleACL",
              "voiceDomainPermission": false,
              "neat": false,
              "webRedirection": {
                "webRedirectionType": "SOME_TYPE",
                "webRedirect": "http://example.com",
                "acl": "SOME_ACL",
                "portalName": "SOME_PORTAL"
            }
          }
          }
        body_format: json
        validate_certs: no
      register: result

    - name: Afficher le résultat
      debug:
        var: result
