---
- name: Créer un profil d'autorisation via l'API REST
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Créer un profil d'autorisation
      uri:
        url: "https://161.1.7.221:9060/ers/config/authorizationprofile"
        method: POST
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
          Authorization: "Basic YWRtaW46T251dGVjaDEMy="
        body: >
          {
            "AuthorizationProfile": {
              "id": "1122334455",
              "name": "MonProfilAuthorization",
              "description": "Description",
              "accessType": "ACCESS_ACCEPT",
              "authzProfileType": "SWITCH",
              "vlan": {
                "nameID": "200",
                "tagID": 1
              }
            }
          }
        body_format: json
        validate_certs: no
      register: result

    - name: Afficher le résultat
      debug:
        var: result
