---

- name: FIREWALLS
  hosts: firewall
  gather_facts: false
  connection: network_cli

  tasks:
    - name: ASA CONFIG
      asa_command:
        commands: show run
      register: output

    - name: SAVE ASA CONFIG
      copy:
        content: "{{ output.stdout[0] }}"
        dest: "/backups/asa_configs/show_run_{{ inventory_hostname }}.txt"

