---
- name: Liste des policy sets
  hosts: localhost
  tasks:
    - name: Appel API pour récupérer la liste des policy sets
      uri:
        url: "https://161.1.7.221:443/api/v1/policy/device-admin/policy-set"
        method: GET
        headers:
          Content-Type: "application/json"
        validate_certs: no
      register: response

    - name: Affichage de la réponse de l'API
      debug:
        var: response
