---
- name: Créer le répertoire de sauvegarde sur localhost
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Créer le répertoire de sauvegarde
      file:
        path: "{{ backup_destination }}"
        state: directory
      vars:
        backup_destination: "~/config_backup"

- name: Backup Cisco Switch Configuration
  hosts: all
  gather_facts: yes
  connection: network_cli
  vars:
    backup_destination: "~/config_backup"
    cli:
      host: "{{ inventory_hostname }}"
      username: "cisco"
      password: "cisco"
      authorize: yes
      auth_pass: "cisco"
  tasks:
    - name: Backup Cisco configuration
      cisco.ios.ios_config:
        provider: "{{ cli }}"
        backup: yes
        backup_options:
          filename: "config_backup_{{ ansible_hostname }}_{{ ansible_date_time.date }}.txt"
          destination: "{{ backup_destination }}"
      delegate_to: localhost

  handlers:
    - name: Print backup directory path
      debug:
        msg: "Configuration backup saved to {{ backup_destination }}"
